baseURL = 'https://scrutin.app/'
languageCode = 'en-us'
title = 'Scrutin'

[params]
  project_name = "Scrutin"
  project_tagline = "/ˈskɹuːtɪn/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
